### ISSUE TITLE
Backgrounds is now completely black

### ISSUE THREAD

**Issue by fuzunspm** [vangware/dark-plus-material#11]
Today, i believe there was an update, so my code background color is turned to complete black. How do i revert back to old color?

**Comment by sksundram** [comment]
It's too dark for my liking. There must be an option to get back the old look.

**Comment by loucyx** [comment]
I see several people asking to go back to the old "low contrast gray", previously I received lots of complaints with the background not being black. I guess I'll rollback to gray and try to add an option for black.

**Comment by loucyx** [comment]
There, is back to gray in 2.0.2. Will add an option in the future for people who want it black.

**Comment by fuzunspm** [comment]
I’m sorry for this, you can’t make everyone happy with color preferences but it would be great for an option switch. Thank you

**Comment by loucyx** [comment]
No worries @fuzunspm 😄 ... I need to think about long time users that like the gray background and maybe don't want a black one.

**Comment by sksundram** [comment]
After the update, the sidebar gets back to the old gray background color but the main editor area still has pure black as the background. How to solve this issue?

**Comment by loucyx** [comment]
Hi @sksundram, in the last version is not pure black, you can check the code, is grey: https://github.com/vangware/dark-plus-material/blob/master/dark-plus-material.json#L29 ... you can customize it to make it lighter if you want adding this in your settings:
```
"workbench.colorCustomizations": {
    "editor.background": "the color you want"
}
```
