### ISSUE TITLE
Highlight color for search should be updated

### ISSUE THREAD

**Issue by MariusVatasoiu** [vangware/dark-plus-material#13]
If you search a HTML tag, the highlight color for search matches with the tags symbols color <>.
Here is an example:
![dark-bug](https://user-images.githubusercontent.com/18071013/55611128-4fa92080-578d-11e9-8c40-97c7384724f4.JPG)
Also, the highlight color doesn't have a good contrast with normal text in HTML files.
![dark-bug-2](https://user-images.githubusercontent.com/18071013/55611481-4ff5eb80-578e-11e9-8a5b-6845ccd295a3.JPG)

**Comment by loucyx** [comment]
I'll let you know as soon as I found the issue and let you know to check it.

**Comment by loucyx** [comment]
Should be resolved in the latest update. Feel free to reopen if it isn't.
