### ISSUE TITLE
Active file is not highlighted in the sidebar anymore

### ISSUE THREAD

**Issue by MariusVatasoiu** [vangware/dark-plus-material#14]
When you open a file and you click in the code area, the current file should be highlighted in the sidebar, but it doesn't work anymore. Also, when you switch between files, the current file should be highlighted in the sidebar.
This functionality worked in 1.x versions.

**Comment by loucyx** [comment]
@MariusVatasoiu I think this is an issue with VSCode itself, not with the theme. Please test other themes in order to confirm. Thanks!

**Comment by MariusVatasoiu** [comment]
@lukeshiru I've tested with other themes and it works, also with the older version of the theme (1.x) it works. I think it's related to the color.

**Comment by loucyx** [comment]
Fixed on latest. Sorry for the long delay, a lot of work lately!
