### ISSUE TITLE
Find and Replace popup no longer displaying correctly

### ISSUE THREAD

**Issue by MatthewJohnSymons** [vangware/dark-plus-material#17]
On the latest version of VSCode. Just updated today and since the update, the find and replace popup now looks like the below, making it very difficult to see the buttons:

![Code_2019-11-16_23-07-10](https://user-images.githubusercontent.com/30142703/69000352-1cec0c80-08c6-11ea-9080-36fc77350002.png)

It works fine when I disable the theme.

**Comment by loucyx** [comment]
Definitely a bug. I'll try to find the place where the color conversion is bugged and try to patch it asap. 

Thanks!

**Comment by kjgalvan** [comment]
Just a heads up, this color is controlled by icon.foreground, I fixed my editor by changing that property to #BDBDBD

**Comment by loucyx** [comment]
Thanks a lot for the help, @kjgalvan! :sparkling_heart:

**Comment by loucyx** [comment]
@MatthewJohnSymons Should be fixed in 2.2.1. Let me know if is not 😄

**Comment by MatthewJohnSymons** [comment]
@lukeshiru Looks good to me :) Thanks for that!

**Comment by loucyx** [comment]
Awesome! Thanks for taking the time!
