### ISSUE TITLE
Active selection highlight color

### ISSUE THREAD

**Issue by ilepn** [vangware/dark-plus-material#19]
Hi there,

Could you kindly consider adjusting the color for active selection highlighting and find match colors?

![image](https://user-images.githubusercontent.com/26382655/83408612-92ab6600-a41b-11ea-9c04-f8145dce6ffc.png)

> Active selection highlighting color is barely visible against the background.

![image](https://user-images.githubusercontent.com/26382655/83408690-b8386f80-a41b-11ea-9172-6d7e0098b345.png)

> Sometimes it's hard to recognize the find matches.
> Even harder is to distinguish if you're having some of the found matches already in active selection.

Otherwise, I just want to express my thanks as this has been my favorite theme for a long time!

Best regards,
Kaedin

**Comment by loucyx** [comment]
Hi, @Kaedin!

Sorry for the late response, lots of work lately. About the changes in colors, I did that in the past with really bad reception in the userbase of the theme. My recomendation for this would be to add that customization in your user settings with a code like this:
```json
"workbench.colorCustomizations": {
  "name.of.property.you.want.to.customize": "#COLOR"
}
```
You can get further info about this settings [here](https://code.visualstudio.com/docs/getstarted/themes).

Thank you!

**Comment by ilepn** [comment]
Hi @lukeshiru,

Thanks for your response! I understand that especially in themes it's hard to please everyone. Thank you as well for the help with how to apply personal customizations on top of the theme! 

Unfortunately, I'm not good at all with colors and graphical designing. I know you're very busy but would you have a recommendation for some good choice of colors to use on those functions mentioned on my original description that would be in line with your theme? :)

Best regards,

**Comment by loucyx** [comment]
Hi @Kaedin! I responded to some person with the same question as you here: https://github.com/vangware/dark-plus-material/issues/20#issuecomment-667453255
