### ISSUE TITLE
editor.renderLineHighlight: "line" - doesn't work anymore

### ISSUE THREAD

**Issue by MariusVatasoiu** [vangware/dark-plus-material#2]
VSCode Version: 1.12.1
Dark+ Material: 1.0.0

Option editor.renderLineHighlight: "line" is not working anymore. The current line is no longer highlighted with a border, it is only highlighted with a background - it's like having the "all" option enabled.

In "Dark+ Material" is like this:
![after](https://cloud.githubusercontent.com/assets/18071013/25837519/fde197e8-3496-11e7-9f1d-bad5537e786f.JPG)
And in "Dark (Visual Studio)" is like this:
![before](https://cloud.githubusercontent.com/assets/18071013/25837536/0cb3ec4e-3497-11e7-9ce9-3c5c2ff5fb86.JPG)
Before the update, the "line" option worked as in the second image (with border).

**Comment by loucyx** [comment]
Temporary fix in fc31a9add5e81320c3166dde62af428dcbb213b3 (v1.0.1) ... VSCode should take the colors in the theme depending on the user settings for the `editor.renderLineHighlight` option, but the theme colors have higher priority.
