### ISSUE TITLE
Unable to change line highligher

### ISSUE THREAD

**Issue by dgoldman-msft** [vangware/dark-plus-material#20]
I love this theme but have some vison problems and I am unable to see any lines that I highlight. Is there a way to implement a way to change the highlighted text to something brighter?

**Comment by loucyx** [comment]
Hi @dgoldman-msft! Is really good to know that you like this theme! About your issue: You can customize colors of any theme by just setting them in your user settings. I believe the properties you want to update are `editor.selectionBackground` and `editor.selectionHighlightBackground`:
```json
"workbench.colorCustomizations": {
  "editor.selectionBackground": "Your Color here in hex format  #RRGGBBAA, for example #ff00ffff is pink",
  "editor.selectionHighlightBackground": "Your Color here in hex format #RRGGBBAA, for example #ff00ffff is pink"
}
```
You have more information [here](https://code.visualstudio.com/docs/getstarted/themes). You can check all the property names an their values of this theme [here](https://github.com/vangware/dark-plus-material/blob/master/dark-plus-material.json#L4-L201).

**Comment by dgoldman-msft** [comment]
You are the man!! THANK YOU!!!
Dave
