### ISSUE TITLE
VScodium availability

### ISSUE THREAD

**Issue by agurenko** [vangware/dark-plus-material#21]
I want to start by saying big thanks for the theme, there is simply no other theme that provides better readability for me. But since few months, your theme is not available in vscodium for some reasons and I'm wondering why is that? All other extensions I use are exactly the same between VS Code and Codium, but your theme. It would be great if it can be installed and updated the same way on codium. Thank you.

**Comment by loucyx** [comment]
I'll investigate, but Dark+ Material is made using VSCode repository as a base, so if something is different between Codium and VSCode then that might be the reason. If there is something I can do on my side I'll try to do it, but if not I would recommend to create an issue in Codium's repo.

Thanks!

**Comment by loucyx** [comment]
Sorry for the late response (lots of work lately), but after some investigation, the actual implementation to make this work would make updating and maintaining even harder.

PRs welcome nonetheless, so if you're interested on supporting Codium and you want to create a PR for that, it will be welcome 👍🏻
