### ISSUE TITLE
Theme Missing in VSCode - Garuda Linux

### ISSUE THREAD

**Issue by riungemaina** [vangware/dark-plus-material#24]
Hello, can't find the theme, this is what comes up when I do the search,
![image](https://user-images.githubusercontent.com/51113345/119564684-bc3e6980-bdb1-11eb-864f-e9a30da32558.png)
is there an alternative way of loading up the theme to vscode. I'm using Garuda Linux which probably has something to do with why the error is coming up..

Please help, my code looks like it's not my code 🤦🏽‍♂️

**Comment by loucyx** [comment]
Hi @castynet!

Try going into the VSCode store directly, and clicking on "Install": https://marketplace.visualstudio.com/items?itemName=vangware.dark-plus-material ... you should configure your distro to open those links with Visual Studio Code.

If that doesn't work, try putting this in the search field: `vangware.dark-plus-material` or `Dark+ Material`

**Comment by riungemaina** [comment]
Hello, still couldn't find it.. If I ever figure out why I'll remember to post the reason here. To fix my issue though, I installed the extension manually, found a tutorial on the interwebs... now my code really looks the part 😊😊
