### ISSUE TITLE
Error messages are hard to read

### ISSUE THREAD

**Issue by pcgeek86** [vangware/dark-plus-material#3]
The grey text on bright red background is nearly impossible to read and kind of hurts my eyes, too. Is the background color for an exception configurable in VSCode?

![screen shot 2017-06-19 at 1 37 54 pm](https://user-images.githubusercontent.com/466713/27304974-c5f519f8-54f4-11e7-97a4-340db32cfa92.png)

Cheers,
Trevor Sullivan

**Comment by loucyx** [comment]
I made it into the default colors for now. The default theme colors are a mess, and the code behind this theme takes the default colors and turns them into material palette. As soon as Microsoft solves those issues, this theme will rock even more :P
