### ISSUE TITLE
Wrong colors in Keyboard Shortcuts page

### ISSUE THREAD

**Issue by mcecode** [vangware/dark-plus-material#30]
Hi, thanks for creating this color theme. I've been using it ever since I've been using VSCode.

I don't use the Keyboard Shortcuts page much these days so I didn't really mind when I saw that the colors were off a while back,

![image](https://user-images.githubusercontent.com/65783406/181288763-5aa1dd8c-464a-4d40-9a38-8a491254d508.png)

but I needed to use it today and had some time, so I investigated and saw that the reason was that the following color settings weren't being set by this theme: `keybindingTable.headerBackground` and `keybindingTable.rowsBackground`.

Of course I can just set it in the `workbench.colorCustomizations` section to my liking, but I also noticed that some color settings being shipped by this theme like `editorOverviewRuler.unicodeForeground` are outdated. So after studying its code a bit and found that the color settings come from the [`base.json`](https://github.com/vangware/dark-plus-material/blob/main/src/base.json) file, I presumed that this file is outdated and set out to try and update it for a PR. However, after trying to find where the values come from starting with [`theme.ts`](https://github.com/microsoft/vscode/blob/main/src/vs/workbench/common/theme.ts) and [`dark_plus.json`](https://github.com/microsoft/vscode/blob/main/extensions/theme-defaults/themes/dark_plus.json), I just couldn't figure out how to generate an updated `base.json` file.

I'd be happy to make that PR if you could point me in the right direction on how to generate an updated `base.json` file, or I could just add the color settings I mentioned above to my `settings.json` if you don't want to update it or support those settings. Either way, thanks for your time 😃

**Comment by loucyx** [comment]
Hi @mcecode! Thanks for reporting this! I haven't updated the theme with the latest VSCode configs for a while now. I'll take a look and try to update it today. Thanks for reporting it!

**Comment by loucyx** [comment]
Fixed on the latest version! Thanks again, @mcecode! :sparkles:
