### ISSUE TITLE
Comparing changes lines

### ISSUE THREAD

**Issue by ilepn** [vangware/dark-plus-material#6]
Hi Developer,

Currently, with the default settings of Dark+ Material theme it is only possible to detect added or removed lines while in compare mode of selected documents in vscode. For example, other themes are able to visualize changes within the lines via using lighter highlighting color for the changed line and more intense color for the changes. In addition, "Palenight" theme is also applying a distinguishable borderline to inline changes which is looking pretty nice and further highlighting the changed areas.

Dark+ Material currently:
![snipaste_2018-06-11_07-52-16](https://user-images.githubusercontent.com/26382655/41215596-b67dcffa-6d59-11e8-8e7e-9a308a89d369.png)

Theme supporting inline change highlighting:
![snipaste_2018-06-11_07-56-14](https://user-images.githubusercontent.com/26382655/41215622-d9143798-6d59-11e8-85d8-776e607eda16.png)

Palenight theme with distinguishable borderlines around each inline change:
![snipaste_2018-06-11_09-21-46](https://user-images.githubusercontent.com/26382655/41215633-ef8a3f7c-6d59-11e8-8a17-0297e9332240.png)

Based on these examples, I hope you could find some room for improvement. For example, it would be great if some of these capabilities are also added to Dark+ Material theme:
 - Colorization tweaks to enable inline change detecting
 - If you're not willing to implement borderlines for inline changes, would you know how to customize this on top of the theme?

Also, do you know how would it be possible to invert the highlighting colors in following scenario: I've selected certain string and the original selection is highlighter with lighter color than the other matches found inside the file. I would like to emphasize the original selection via highlighting it with more intense color so that it would pop out more than the other matches.
![image](https://user-images.githubusercontent.com/26382655/41215843-e1dc3dd4-6d5a-11e8-9383-1bb3a57eee3d.png)

Also, if you know how to enable borderlines for current selection and matches in the current file (not just comparison as given in example above)?

Sorry for asking also such trivial questions and somewhat unrelated to development of the extension!

Best regards,
Kaedin

**Comment by loucyx** [comment]
I'll take a look at the automatic theme generator and see if I can add a color mapping to achieve this behavior. Thanks for noticing the issue @Kaedin!
