### ISSUE TITLE
HTML: match the color of the symbols <> with the color of the tag name

### ISSUE THREAD

**Issue by MariusVatasoiu** [vangware/dark-plus-material#7]
Hi,
I have a proposal for .html highlighting. I think you could try to change the way that html tags are colored. Right now, the symbols ("<", ">", "/>", "</") are light grey (blueish 😅), while the name of the tag is blue. 
If the symbols would be also blue, I think you could read easily through the lines, because it would have less variations of colors. Besides that, that light grey is very similar with the grey used for text.

I've attached below a simulation:

![before-after](https://user-images.githubusercontent.com/18071013/42117740-2958859a-7c07-11e8-918b-04e7e83a3197.png)

Keep up the good work! This is my favorite theme for some time. 👍

**Comment by loucyx** [comment]
Hi @MariusVatasoiu and thanks for your feedback!

This theme takes the `.json` files from the official VSCode repo and then transforms every color from Dark+ theme to the material palette equivalent. If you take a look at the default Dark+ theme, you'll notice that the `<` and `>` symbols are "grey" and the text is blue in html tags, so Dark+ Material should keep that as it is right now.

Thanks again for your feedback and if this becomes a constant requirement in Dark+ Material users, I'll try to implement it.

Best regards!
