### ISSUE TITLE
Theme doesn't work anymore in version 1.27.2

### ISSUE THREAD

**Issue by MariusVatasoiu** [vangware/dark-plus-material#8]
There is a problem with the theme in the VS Code 1.27.2. It is disabled automatically and you can't reactivated. The button "Reload" is active, but if you click it, it will reload the app, but without any effect. I faced this issue on two different computers today.

**Comment by loucyx** [comment]
Thanks for the letting me know, @MariusVatasoiu .... it was working on my Mac, but I just checked on my PC and is broken for some reason. I'll check it out.

**Comment by sabihoshi** [comment]
Thought I was the only one experiencing this, even the latest exploration build with fresh settings and no other extensions is also broken on it.

Upon checking, it doesn't seem to be activating the extension according to Extension Host logs.
It has no entry in there at all.

**Comment by pjpollina** [comment]
Thought I was going crazy, glad it's not just me.

**Comment by ghost** [comment]
me too having same problem from today morning on my windows Dell laptop

**Comment by loucyx** [comment]
@MariusVatasoiu, @pjpollina, @loliprotector and @rajeshjeshar, this should be fixed if you update to v1.4.2, please let me know if it works :)

**Comment by ghost** [comment]
started working just now thanks

**Comment by loucyx** [comment]
I'll wait to a second confirmation and I'll close the ticket :)

**Comment by ghost** [comment]
It works again for me

**Comment by MariusVatasoiu** [comment]
It works now, I think you can close the issue now. Thanks a lot for your work 👍.

**Comment by loucyx** [comment]
Awesome! Thank you all for the feedback! :D
