### ISSUE TITLE
VISIBILITY PROBLEM IN Vscode 1.3.1

### ISSUE THREAD

**Issue by ghost** [vangware/dark-plus-material#9]
![image](https://user-images.githubusercontent.com/39165538/52688973-91340100-2f7e-11e9-9907-916f676b0e61.png)

importing libraries are not visible from the latest vscode update,
[the default system dark theme works fine]

**Comment by loucyx** [comment]
@rajeshjeshar thanks for this bug report! I'll work on improving the contrast!

**Comment by loucyx** [comment]
This should be resolved in v2.0.3 with a color with better contrast (Indigo instead of Teal). Please confirm @rajeshjeshar! :)

**Comment by ghost** [comment]
@lukeshiru 2.0.3 and 2.0.4 both worked well

**Comment by loucyx** [comment]
Thanks for your priceless feedback, @rajeshjeshar ! Closing now! ❤️
